import { _electron as electron, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdtemp, rm, readFile, access } from 'node:fs/promises'
import path from 'node:path'
import { testScratch, closeTestApp, packagedExecutable } from './helpers/electron-harness.mjs'
const scratch = await testScratch(), dir = await mkdtemp(path.join(scratch, 'elevenmd-support-'))
const env = { ...process.env, NOTEPAD_USER_DATA_DIR: path.join(dir, 'profile') }; delete env.ELECTRON_RUN_AS_NODE; delete env.NOTEPAD_DEV_URL
const exportPath = path.join(dir, 'safe-export.json')
let app
try {
  app = await electron.launch({ executablePath: packagedExecutable(), args: [], env })
  const page = await app.firstWindow(), errors = []
  page.on('pageerror', error => errors.push(error.message))
  await expect(page.getByRole('tab')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Choose diagnostics privacy' })).toBeVisible()
  assert.equal((await page.evaluate(() => notepad.diagnosticsState())).consent, null)
  await assert.rejects(access(path.join(dir, 'profile', 'diagnostics.json')))
  await page.getByRole('button', { name: 'Choose diagnostics privacy' }).click()
  await page.getByRole('button', { name: 'Enable sanitized local logs' }).click()
  await page.locator('.tiptap').fill('PRIVATE DOCUMENT SENTINEL')
  await page.getByRole('button', { name: 'Bold', exact: true }).click()
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('PRIVATE SEARCH SENTINEL')
  await page.keyboard.press('Control+f')
  await page.getByRole('textbox', { name: 'Find text' }).fill('PRIVATE SEARCH')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Close find', exact: true }).click()
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, path.join(dir, 'private-note.md'))
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('tab')).toHaveAttribute('data-dirty', 'false')
  let report = await page.evaluate(() => notepad.diagnosticsInspect())
  assert.ok(report.events.some(e => e.type === 'formatting' && e.action === 'bold'))
  assert.ok(report.events.some(e => e.type === 'document_save' && e.outcome === 'success'))
  assert.ok(!JSON.stringify(report).includes('PRIVATE'))
  assert.ok(!JSON.stringify(report).includes(dir))
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, exportPath)
  assert.equal(await page.evaluate(() => notepad.diagnosticsExport()), true)
  const exported = await readFile(exportPath, 'utf8'); assert.ok(!exported.includes('PRIVATE')); assert.ok(!exported.includes(dir))
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Diagnostics & privacy' }).click()
  await page.getByRole('button', { name: 'Inspect logs' }).click()
  await expect(page.locator('#diagnostics-preview')).toContainText('document_save')
  await page.screenshot({ path: path.join(scratch, 'elevenmd-diagnostics-qa.png') })
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await app.evaluate(({ dialog, shell }) => { globalThis.reportURLs = []; shell.openExternal = async url => { globalThis.reportURLs.push(url) }; dialog.showMessageBox = async () => ({ response: 1 }) })
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Report a bug' }).click()
  await page.getByRole('textbox', { name: 'Report title' }).fill('A reproducible formatting bug')
  await page.getByRole('textbox', { name: 'Steps to reproduce' }).fill('Select a fixture and click Bold. Contact hidden@example.com')
  await page.getByRole('textbox', { name: 'Expected behavior' }).fill('Bold text')
  await page.getByRole('textbox', { name: 'Actual behavior' }).fill('Fixture failure')
  await page.getByRole('checkbox', { name: 'Include sanitized diagnostics' }).check()
  await page.getByRole('button', { name: 'Review report' }).click()
  await expect(page.locator('#bug-preview')).not.toContainText('hidden@example.com')
  await expect(page.locator('#bug-preview')).not.toContainText('PRIVATE')
  await expect(page.locator('#bug-preview')).toContainText('Sanitized diagnostics')
  await page.getByRole('button', { name: 'Open GitHub issue' }).click()
  assert.deepEqual(await app.evaluate(() => globalThis.reportURLs), [])
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0 }) })
  const reviewedBody = await page.locator('#bug-preview').textContent()
  await page.getByRole('button', { name: 'Open GitHub issue' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const urls = await app.evaluate(() => globalThis.reportURLs)
  assert.equal(urls.length, 1); const url = new URL(urls[0]); assert.equal(url.pathname, '/FullPotionStack/ElevenMD/issues/new')
  assert.equal(`${url.searchParams.get('title')}\n\n${url.searchParams.get('body')}`, reviewedBody)
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Check updates', exact: true }).click()
  await expect(page.locator('#update-description')).toContainText(/up to date|no published releases|Could not check|Unable to check/, { timeout: 20000 })
  await page.screenshot({ path: path.join(scratch, 'elevenmd-updates-qa.png') })
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Diagnostics & privacy' }).click()
  await page.getByRole('button', { name: 'Disable and delete logs' }).click()
  report = await page.evaluate(() => notepad.diagnosticsInspect())
  assert.equal(report.consent, false); assert.equal(report.events.length, 0)
  const disk = JSON.parse(await readFile(path.join(dir, 'profile', 'diagnostics.json'), 'utf8'))
  assert.equal(disk.consent, false); assert.deepEqual(disk.events, [])
  assert.deepEqual(errors, [])
  console.log('PASS actual packaged IPC: default off/no logs; explicit consent; enum-only writing/file breadcrumbs; inspect/export; exact redacted public issue draft; native cancellation; no issue submission; live release check; durable revocation; no renderer errors')
} finally { await closeTestApp(app); await rm(dir, { recursive: true, force: true }) }
