import { _electron as electron, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdtemp, rm, readFile, access } from 'node:fs/promises'
import path from 'node:path'
import { testScratch, closeTestApp, packagedExecutable } from './helpers/electron-harness.mjs'
const scratch = await testScratch(), dir = await mkdtemp(path.join(scratch, 'elevenmd-support-'))
const env = { ...process.env, NOTEPAD_USER_DATA_DIR: path.join(dir, 'profile') }; delete env.ELECTRON_RUN_AS_NODE; delete env.NOTEPAD_DEV_URL
const exportPath = path.join(dir, 'safe-export.json')
const source = process.argv.includes('--source'), require = createRequire(import.meta.url)
let app
try {
  app = await electron.launch({ executablePath: source ? require('electron') : packagedExecutable(), args: source ? ['.'] : [], env })
  const page = await app.firstWindow(), errors = []
  page.on('pageerror', error => errors.push(error.message))
  await expect(page.getByRole('tab')).toBeVisible()
  await expect(page.locator('footer #privacy-choice')).toHaveCount(0)
  assert.equal((await page.evaluate(() => notepad.diagnosticsState())).consent, null)
  await assert.rejects(access(path.join(dir, 'profile', 'diagnostics.json')))
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Privacy & diagnostics', exact: true }).click()
  await page.getByRole('button', { name: 'Enable sanitized local logs' }).click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.locator('.tiptap').fill('PRIVATE DOCUMENT SENTINEL')
  await page.getByRole('button', { name: 'Bold', exact: true }).click()
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('PRIVATE SEARCH SENTINEL')
  await page.keyboard.press('Control+f')
  await page.getByRole('textbox', { name: 'Find text' }).fill('PRIVATE SEARCH')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Close find', exact: true }).click()
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, path.join(dir, 'private-note.md'))
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('tab')).toHaveAttribute('data-dirty', 'false')
  let report = await page.evaluate(() => notepad.diagnosticsInspect())
  assert.ok(report.events.some(e => e.type === 'formatting' && e.action === 'bold'))
  assert.ok(report.events.some(e => e.type === 'document_save' && e.outcome === 'success'))
  assert.ok(!JSON.stringify(report).includes('PRIVATE'))
  assert.ok(!JSON.stringify(report).includes(dir))
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, exportPath)
  assert.equal(await page.evaluate(() => notepad.diagnosticsExport()), true)
  const exported = await readFile(exportPath, 'utf8'); assert.ok(!exported.includes('PRIVATE')); assert.ok(!exported.includes(dir))
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Privacy & diagnostics', exact: true }).click()
  await page.getByRole('button', { name: 'Inspect logs' }).click()
  await expect(page.locator('#diagnostics-preview')).toContainText('document_save')
  await page.screenshot({ path: path.join(scratch, 'elevenmd-diagnostics-qa.png') })
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  assert.equal(await page.evaluate(() => 'reportBug' in notepad || 'prepareBugReport' in notepad || 'reportingState' in notepad), false)
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Report a bug', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Help', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Check updates', exact: true }).click()
  await expect(page.locator('#update-description')).toContainText(/up to date|no published releases|Could not check|Unable to check/, { timeout: 20000 })
  await page.screenshot({ path: path.join(scratch, 'elevenmd-updates-qa.png') })
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Privacy & diagnostics', exact: true }).click()
  await page.getByRole('button', { name: 'Disable and delete logs' }).click()
  report = await page.evaluate(() => notepad.diagnosticsInspect())
  assert.equal(report.consent, false); assert.equal(report.events.length, 0)
  const disk = JSON.parse(await readFile(path.join(dir, 'profile', 'diagnostics.json'), 'utf8'))
  assert.equal(disk.consent, false); assert.deepEqual(disk.events, [])
  assert.deepEqual(errors, [])
  console.log('PASS actual Electron IPC/disk: tabbed Settings privacy; default off; explicit consent; enum-only breadcrumbs; inspect/export; no reporting APIs or menu; durable revocation; no renderer errors. No email was submitted.')
} finally { await closeTestApp(app); await rm(dir, { recursive: true, force: true }) }
