import { test, expect } from '@playwright/test'

test('formatting toolbar edits headings, bold, tasks and tables; menus expose file actions and preferences', async ({ page }) => {
  await page.goto('/')
  await page.locator('.tiptap').fill('A simple note')
  await page.keyboard.press('Control+a')
  await page.getByRole('button', { name: 'Bold', exact: true }).click()
  await expect(page.locator('.tiptap strong')).toHaveText('A simple note')
  await page.getByRole('combobox', { name: 'Block style' }).selectOption('h1')
  await expect(page.locator('.tiptap h1')).toHaveText('A simple note')
  await page.getByRole('button', { name: 'New tab' }).click()
  await page.getByRole('button', { name: 'Task list', exact: true }).click()
  await page.keyboard.type('Ship Windows alpha')
  await expect(page.locator('.tiptap input[type=checkbox]')).toBeVisible()
  const checkboxBox = await page.locator('.tiptap input[type=checkbox]').boundingBox()
  const textBox = await page.locator('.tiptap li p').first().boundingBox()
  expect(Math.abs(checkboxBox.y - textBox.y)).toBeLessThan(12)
  await page.locator('.tiptap input[type=checkbox]').check()
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Markdown source' })).toHaveValue(/\[x\] Ship Windows alpha/)
  await page.getByRole('button', { name: 'New tab' }).click()
  await page.getByRole('button', { name: 'Formatted', exact: true }).click()
  await page.getByRole('button', { name: 'Insert table', exact: true }).click()
  await expect(page.locator('.tiptap table')).toBeVisible()
  await page.getByRole('button', { name: 'File', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: /Save as/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('combobox', { name: 'App theme' }).selectOption('dark')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.keyboard.press('Control+=')
  await expect(page.getByRole('button', { name: '110%', exact: true })).toBeVisible()
})
