import { test, expect } from '@playwright/test'

for (const sequence of [['Task list', 'Bullet list'], ['Task list', 'Numbered list'], ['Bullet list', 'Task list'], ['Numbered list', 'Task list'], ['Bullet list', 'Numbered list'], ['Numbered list', 'Bullet list']]) {
  test(`list conversion stays consistent: ${sequence.join(' → ')}`, async ({ page }) => {
    await page.goto('/')
    await page.locator('.tiptap').fill('Ship the note')
    await page.keyboard.press('Control+a')
    for (const name of sequence) await page.getByRole('button', { name, exact: true }).click()
    const task = sequence.at(-1) === 'Task list'
    await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(task ? 1 : 0)
    await expect(page.locator('.tiptap li')).toHaveCount(1)
    await page.getByRole('button', { name: 'Source', exact: true }).click()
    const source = await page.locator('#source').inputValue()
    console.log(JSON.stringify({ sequence, source }))
    expect(source).not.toMatch(/\\\[[ x]\]|\[[ x]\].*\[[ x]\]/)
    if (task) expect(source).toMatch(/^- \[ \] Ship the note/)
    else expect(source).not.toContain('[ ]')
    await page.getByRole('button', { name: 'Preview', exact: true }).click()
    await expect(page.locator('#preview li')).toHaveCount(1)
    await expect(page.locator('#preview input[type=checkbox]')).toHaveCount(task ? 1 : 0)
    await expect(page.locator('#preview')).not.toContainText('[ ]')
    await expect(page.locator('#preview li')).toContainText('Ship the note')
    await page.getByRole('button', { name: 'Formatted', exact: true }).click()
    await expect(page.locator('.tiptap li')).toHaveCount(1)
    await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(task ? 1 : 0)
  })
}

test('empty task survives Preview, source reload, and formatted parsing', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Task list', exact: true }).click()
  await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('#preview input[type=checkbox]')).toHaveCount(1)
  await expect(page.locator('#preview')).not.toContainText('[ ]')
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.locator('#source').fill('- [x]\n')
  await page.getByRole('button', { name: 'Formatted', exact: true }).click()
  await expect(page.locator('.tiptap input[type=checkbox]')).toBeChecked()
})

for (const markdown of ['- [ ]\n- [x] Finished\n- [ ]\n', '- [x] Finished\n- [ ]\n- [ ] Pending\n']) {
  test(`mixed empty and nonempty tasks remain one list: ${JSON.stringify(markdown)}`, async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: 'Source', exact: true }).click()
    await page.getByRole('textbox', { name: 'Markdown source' }).fill(markdown)
    await page.getByRole('button', { name: 'Formatted', exact: true }).click()
    await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(3)
    await expect(page.locator('.tiptap > ul[data-type=taskList]')).toHaveCount(1)
    await page.getByRole('button', { name: 'Preview', exact: true }).click()
    await expect(page.locator('#preview input[type=checkbox]')).toHaveCount(3)
    await expect(page.locator('#preview > ul')).toHaveCount(1)
  })
}

test('escaped checkbox-looking text stays literal in Preview', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.locator('#source').fill('- \\[ \\]\n\n```md\n- [ ]\n```\n')
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('#preview input')).toHaveCount(0)
  await expect(page.locator('#preview code')).toHaveText('- [ ]\n')
})

test('list conversion preserves bold text, nested lists, neighboring headings and undo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('- [x] **Finished**\n  - [ ]\n  - nested bullet\n- [ ] Pending\n\n# Untouched\n')
  await page.getByRole('button', { name: 'Formatted', exact: true }).click()
  await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(3)
  await page.locator('.tiptap strong', { hasText: 'Finished' }).click()
  await page.getByRole('button', { name: 'Bullet list', exact: true }).click()
  await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(1)
  await expect(page.locator('.tiptap strong')).toHaveText('Finished')
  await expect(page.locator('.tiptap h1')).toHaveText('Untouched')
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('#preview input[type=checkbox]')).toHaveCount(1)
  await expect(page.locator('#preview strong')).toHaveText('Finished')
  await expect(page.locator('#preview h1')).toHaveText('Untouched')
  await page.getByRole('button', { name: 'Formatted', exact: true }).click()
  await page.locator('.tiptap').press('Control+z')
  await expect(page.locator('.tiptap input[type=checkbox]')).toHaveCount(3)
  await expect(page.locator('.tiptap input[type=checkbox]').first()).toBeChecked()
  await expect(page.locator('.tiptap strong')).toHaveText('Finished')
  await expect(page.locator('.tiptap h1')).toHaveText('Untouched')
})

test('task list alone has identical checked state in formatted and Preview', async ({ page }) => {
  await page.goto('/')
  await page.locator('.tiptap').fill('A completed task')
  await page.keyboard.press('Control+a')
  await page.getByRole('button', { name: 'Task list', exact: true }).click()
  await page.locator('.tiptap input[type=checkbox]').check()
  const richCheckbox = await page.locator('.tiptap input[type=checkbox]').boundingBox()
  const richText = await page.locator('.tiptap li p').boundingBox()
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('#preview input[type=checkbox]')).toBeChecked()
  await expect(page.locator('#preview .task-content')).toHaveCSS('text-decoration-line', 'line-through')
  const previewCheckbox = await page.locator('#preview input[type=checkbox]').boundingBox()
  const previewText = await page.locator('#preview .task-content').boundingBox()
  expect(Math.abs((richText.x - richCheckbox.x) - (previewText.x - previewCheckbox.x))).toBeLessThan(3)
  expect(Math.abs(previewCheckbox.y - previewText.y)).toBeLessThan(12)
  await expect(page.locator('#preview')).not.toContainText('[x]')
})
